### ISSUE TITLE
MSI Z87-G43 Gaming - Haswell Mobo without 4G Decoding Entry

### ISSUE THREAD

**Issue by Tatsun0x05rd1** [xCuri0/ReBarUEFI#112] opened 2024-01-06 06:40 UTC
**System**
 - Motherboard: [MSI Z87-G43 Gaming](https://www.msi.com/Motherboard/Z87-G43-GAMING/Specification)
 - BIOS Version: [AMI BIOS A.7](https://download.msi.com/bos_exe/mb/7816vA7.zip) (Within UEFI firmware it shows Version 10.7)
 - GPU: [MSI Armor RX 580 8GB](https://www.msi.com/Graphics-Card/Radeon-RX-580-ARMOR-8G-OC/Specification)
 - [✔] CSM is turned off. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [❓] 4G decoding is enabled. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [✔] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed. Since this is an MSI board, no DSDT Patching was done
 - [✔] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

After following the steps up to flashing the BIOS/UEFI firmware, I'm still not able to view the 4G Decod. I tried looking to see if there is any hidden option but all I found was a string. Based on the decoded text, the entry should be right above the PCI subsystem entry "PEG #" which sits above "PCI Latency Timer".

![Offset 39D9D](https://github.com/xCuri0/ReBarUEFI/assets/12003408/2e71d750-ffe2-4ea8-bdaa-86b73f832ffe)

Here's the bin file
[97E409E6-4CC1-11D9-81F6-000000000000_Setup_Compressed_body.zip](https://github.com/xCuri0/ReBarUEFI/files/13848605/97E409E6-4CC1-11D9-81F6-000000000000_Setup_Compressed_body.zip)

I'm able to boot into the custom GRUB efi via flash drive, but I don't know the offset related to my mobo.

Also, I'm able to enable up to 1 GB Rebar and my performance in games like Resident Evil 4 (Remake) has better 1% lows (better overall frames).

![RX580 Rebar](https://github.com/xCuri0/ReBarUEFI/assets/12003408/ae38711b-a703-46ce-b8d1-b6619fa30719)

Lastly, here's a copy of the UEFI firmware modded with the Haswell USB 3 patch and the provided patches.txt
[E7816IMS.zip](https://github.com/xCuri0/ReBarUEFI/files/13848615/E7816IMS.zip)

**Comment by xCuri0** [comment] 2024-01-06 15:01
Duplicate of #14

**Closed by xCuri0** 2024-01-06 15:01 UTC
