### ISSUE TITLE
ASUS Z87-A - No 4G Decode option/support?

### ISSUE THREAD

**Issue by xYuuna** [xCuri0/ReBarUEFI#76] opened 2023-08-16 03:43 UTC
**System**
 - Motherboard: ASUS Z87-A
 - BIOS Version: 2103
 - GPU: RX580 8GB
 - [Y] CSM is turned off
 - [N] 4G decoding is enabled
 - [N] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [Y] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**
Hi,

I am able to set the Resizable Bar to 1GB, but anything higher will result in black screen. I guess this means my motherboard doesn't actually have 4G decode enabled. (GPU-Z was reporting 'Yes') 

I exported the IFR text and couldn't find the 'Above 4G Decoding' option, the only reference is in the BIOS strings. 
I read in other bug reports that swapping the pcihostbridge and/or pcibus modules could potentially work? Checking other Asus Z87 boards, couldn't find 4G either. (I did find 'Max TOLUD' in the bios file, not sure what to do with this? it's set to 'Dynamic')

Is there anything else I can try? I've been checking the DSDT patching guide but I'm not sure if I understand it correctly. So Without 4G decode bios support, I can only get this working in Linux?

Thanks!

![image](https://github.com/xCuri0/ReBarUEFI/assets/130493817/37c25233-fe97-4417-8d63-c44b67994e32)

**Comment by xCuri0** [comment] 2023-08-16 04:40
@xYuuna 

> So Without 4G decode bios support, I can only get this working in Linux?
yes to my knowledge, it is technically possible to re allocate the GPU to above 4GB through a custom bootloader though if anyone wants to try that

duplicate of #14

**Closed by xCuri0** 2023-08-16 04:40 UTC
