### ISSUE TITLE
Asus H81M-D v1 4g decode is in the strings but not in the text file

### ISSUE THREAD

**Issue by NoUserNameForYou** [xCuri0/ReBarUEFI#36] opened 2023-03-04 16:19 UTC
**System**
 - Asus h81m-D rev 1. (Has pcie 2.0) Is 4g decoding only pcie 3.0+?
 - custom made 3602 bios with microde 6 for all core turbo + nvme patch + csm always off (oprom is legacy first, is it correct?)
 - 3080ti + e3 1246v3
 - [ ] UEFIPatch is applied (see README for more information) - Don'T know what that is. I'm not in that stage yet.
 
-----------

I remember changing some var settings in order to flash the bios with fpt with the grub shell. 

UEFItool finds the 4g decode in this guid: "Section_Freeform_subtype_GUID_97E409E6-4CC1-11D9-81F6-000000000000_Setup_Setup_body" but its text file doesn't have it.
AMIBCP4 in bios strings section states "0x0F84 Above 4G decoding" and "0x0F85 Enable or disables 64 bit capable devices to be decoded..." its text explanation.

There's also "0x079D Enable or disable memory map above 4G" string when I search for "above".

When I look at the empty section under "main" in Setup confiuration part, I can't see anything related to 4g decoding. Can I patch in strings in there? Am I SOL?

I have a CH341a that I previously used to bring myself back from a brick. I'm willing to experiment.

Please help me. Thank you.

Edit: Here's my bios in case someone helps me with enabling 4g+rebar and/or teaches me how while they do it.

[nvme6csm.zip](https://github.com/xCuri0/ReBarUEFI/files/10889230/nvme6csm.zip)

edit2: For example if I want to use setup_var commands from the grub shell what am I supposed to type for 0x0f84 and 0x0f85?
I don't know about those little endians and what not...

**Comment by xCuri0** [comment] 2023-03-04 17:56
Duplicate of #14

**Closed by xCuri0** 2023-03-04 17:56 UTC

**Comment by NoUserNameForYou** [comment] 2023-03-04 18:06
Thanks mate. I also posted in your thread on winraid. Apparently some guy was able to patch in strings in his bios. 

https://winraid.level1techs.com/t/add-option-in-ami-uefi-bios-menu-how-to/31609/

Can you at least direct me in the correct path so I can experiment?

**Comment by NoUserNameForYou** [comment] 2023-03-04 19:44
Oh I see you said 4gb can be patched with asm code but you're not planning it.

Well thanks for your efforts anyway, I was able to activate 1GB resizable bar.

**Comment by xCuri0** [comment] 2023-03-05 04:37
@NoUserNameForYou 

>Oh I see you said 4gb can be patched with asm code but you're not planning it.

It's very complicated and I probably won't do it, best to try another way like what you linked
