### ISSUE TITLE
Gigabyte B365M D3H 2+Gb ReBar problem

### ISSUE THREAD

**Issue by xxxviom** [xCuri0/ReBarUEFI#66] opened 2023-07-05 12:49 UTC
**System**
 - Motherboard: Gigabyte B365M D3H
 - BIOS Version: F1
 - GPU: Intel ARC A750
 - [x] CSM is turned off
 - [x] 4G decoding is enabled in BIOS
 - [x] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). Image patched, replaced 8 bytes.
 - [x] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

Resizable bar not oficcially supported in any BIOS version.

ReBarState - 1Gb. GPU-Z shows only YES, BAR=1024. ARC Control shows that Resizable Bar supported, but NOT switched ON in motherboard BIOS. System boots OK and everything works.
ReBarState - 2Gb. Colorfull white noise screen on booting and PC stucked.
ReBarState - 4+Gb. 5 beeps after power on, no signal to monitor, but according to sounds - Windows 11 starting OK.

Any help?

**Comment by xCuri0** [comment] 2023-07-05 13:00
Duplicate of #4

**Closed by xCuri0** 2023-07-05 13:00 UTC
