### ISSUE TITLE
Gigabyte GA-Z170-HD3 UEFIPatch works, but no display output with 4GB+

### ISSUE THREAD

**Issue by Koenigseggs-and-Crypto** [xCuri0/ReBarUEFI#84] opened 2023-09-17 10:28 UTC
**System**
 - Motherboard: Gigabyte GA-Z170-HD3
 - BIOS Version: F22f
 - GPU: RTX 3070
 - [X ] CSM is turned off
 - [X ] 4G decoding is enabled
 - [X ] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [ X] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

Intel Core i5-6600k is the CPU. Couldn't apply DSDT patch as AMIBoardInfo didn't exist, AMIBoardInfo2 exists but doesn't seem valid for DSDT patching. 4G Decoding seems to be working as PCI Express Root Complex is under Large Memory in device management (however RTX 3070 is not). As title, system boots with 4GB+ ReBARState, but without any display output whatsoever even after booting into Windows and (presumably) logging in. 1GB patch works with GPU-Z showing all green ticks for REBAR, 2GB fails to POST.

**Comment by xCuri0** [comment] 2023-09-17 12:14
Duplicate of #4

You could try connecting monitor to iGPU and enabling iGPU in BIOS. It should work then and RTX 3070 output will work in Windows

**Closed by xCuri0** 2023-09-17 12:15 UTC
